# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compengine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='cancellation_fee',
            field=models.FloatField(null=True),
        ),
    ]
